import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const build=path.resolve(process.argv[2]??'build/render-study');
const {GlStats,bufferSourceBytes}=await import(pathToFileURL(path.join(build,'gl_stats.js')));
const bytes=new Uint8Array(20),floats=new Float32Array(10),view=new DataView(bytes.buffer,3,12);
assert.equal(bufferSourceBytes(bytes),20);assert.equal(bufferSourceBytes(floats,2,3),12);
assert.equal(bufferSourceBytes(floats,2),32);assert.equal(bufferSourceBytes(floats,2,0),32);
assert.equal(bufferSourceBytes(view,2,3),3);assert.equal(bufferSourceBytes(view,2),10);
assert.equal(bufferSourceBytes(bytes.buffer),20);assert.equal(bufferSourceBytes(new SharedArrayBuffer(8)),8);
assert.equal(bufferSourceBytes(floats,10),0);
for(const [offset,length]of [[-1,0],[0,-1],[1.5,0],[0,NaN],[11,0],[9,2]])assert.equal(bufferSourceBytes(floats,offset,length),null);
assert.equal(bufferSourceBytes(bytes.buffer,1),null);
const names=['bufferData','bufferSubData','drawArrays','drawElements','drawArraysInstanced','drawElementsInstanced','drawRangeElements'];
const calls=[];
const prototype=Object.fromEntries(names.map(name=>[name,function(...args){assert.equal(this,gl);calls.push({name,args});}]));
const gl=Object.create(prototype),original=names.map(name=>gl[name]),observer=new GlStats(gl);
assert.throws(()=>new GlStats(gl));assert.throws(()=>observer.end());
gl.bufferData(1,floats,2);assert.equal(observer.uploadBytes,0);assert.equal(calls.length,1);
observer.begin();assert.throws(()=>observer.begin());assert.throws(()=>observer.resetTotals());
gl.bufferData(1,1024,2);gl.bufferData(1,null,2);gl.bufferData(1,floats,2);
gl.bufferData(1,floats,2,2);gl.bufferData(1,floats,2,2,3);
gl.bufferSubData(1,4,bytes);gl.bufferSubData(1,4,view,2);gl.bufferSubData(1,4,floats,2,3);
gl.drawArrays(1,0,3);gl.drawElements(1,6,2,0);gl.drawArraysInstanced(1,0,3,10);
gl.drawElementsInstanced(1,6,2,0,10);gl.drawRangeElements(1,0,6,6,2,0);observer.end();
assert.equal(observer.valid,true);assert.equal(observer.uploadBytes,40+32+12+20+10+12);
assert.equal(observer.drawCalls,5);assert.equal(observer.bufferDataCalls,5);assert.equal(observer.bufferSubDataCalls,3);
assert.deepEqual(calls.slice(1,9).map(call=>call.args.length),[3,3,3,4,5,3,4,5]);
assert.equal(calls[5].args[1],floats);assert.deepEqual(calls[5].args,[1,floats,2,2,3]);
assert.equal(calls[7].args[2],view);assert.deepEqual(calls[7].args,[1,4,view,2]);
const totals=observer.report();assert.equal(totals.totalUploadBytes,126);assert.equal(totals.totalDrawCalls,5);assert.equal(totals.sections,1);
observer.begin();gl.drawArrays(1,0,3);observer.end();assert.equal(observer.uploadBytes,0);assert.equal(observer.drawCalls,1);
assert.equal(observer.report().totalDrawCalls,6);observer.resetTotals();assert.equal(observer.report().sections,0);
observer.dispose();observer.dispose();assert.throws(()=>observer.begin());assert.throws(()=>observer.resetTotals());
for(let i=0;i<names.length;++i){assert.equal(gl[names[i]],original[i]);assert.equal(Object.hasOwn(gl,names[i]),false);}
// Restore an existing own method's exact descriptor, including enumerability.
Object.defineProperty(gl,'bufferData',{value:prototype.bufferData,configurable:true,writable:true,enumerable:false});
const descriptor=Object.getOwnPropertyDescriptor(gl,'bufferData'),again=new GlStats(gl);
again.begin();gl.bufferSubData(1,0,floats,100);again.end();assert.equal(again.valid,false);assert.throws(()=>again.resetTotals());
again.dispose();assert.deepEqual(Object.getOwnPropertyDescriptor(gl,'bufferData'),descriptor);
console.log('GL observation: byte/element offsets, zero-length defaults, exact forwarding, submitted draws, scopes, invalid metrics and descriptor restoration PASS');
