import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const entry = pathToFileURL(resolve(process.argv[2] ?? 'build/wasm-debug/package/index.mjs'));
const { createSilk, limits } = await import(entry);
const engine = await createSilk();
assert.equal(engine.version, '0.4.0');
assert.equal(engine.memory.linearMemoryBytes, 64*1024*1024);
assert.equal(limits.polygonVertices, 8);
const config = { bodyCapacity: 2, gravity: { x: 0, y: -9.81 } };
const world = engine.createWorld(config);
assert(world);
assert.equal(world.memory.arenaBytes, engine.worldMemoryBytes(config));
assert.equal(world.configuration.substepCount, 4);
const circle = engine.circle(1);
assert.equal(engine.none().kind, 'none');
assert(engine.isShapeValid(circle));
assert.equal(engine.isShapeValid({}), false);
assert.equal(engine.massData(circle).inertiaPerUnitMass, 0.5);
assert.deepEqual(engine.shapeAabb(circle, { position: { x: 3, y: 2 } }),
  { lower: { x: 2, y: 1 }, upper: { x: 4, y: 3 } });
assert(engine.shapeContainsPoint(circle, {}, { x: 0, y: 0 }));
assert.equal(engine.shapeRayCast(circle, {}, { origin: { x: 0, y: 0 }, translation: { x: 3, y: 0 } }), null);
assert.equal(engine.shapeRayCast(circle, {}, { origin: { x: -2, y: 0 }, translation: { x: 4, y: 0 } }).fraction, 0.25);
assert.equal(engine.circle(-1), null);
assert.throws(() => engine.polygon(new Array(4)), TypeError);
const triangle = engine.polygon([{ x: 0, y: 0 }, { x: 2, y: 0 }, { x: 0, y: 2 }]);
assert(triangle); assert.equal(triangle.vertices.length, 3);
const body = world.createBody({ mass: 1, shape: circle });
assert(body);
assert.equal(world.readBody(body).inertia, 0.5);
for (const value of [NaN, Infinity, -Infinity, 1e100, '1', null, true, {}, [], 1n]) {
  assert.throws(() => world.setMass(body, value), TypeError);
  assert.throws(() => world.step(value), TypeError);
  assert.throws(() => world.createBody({ mass: value }), TypeError);
  assert.throws(() => engine.createWorld({ bodyCapacity: 2, linearDrag: value }), TypeError);
}
for (const value of [0, -1, 1e-45]) assert.equal(world.step(value), false);
for (const value of [-1, 1.5, 2**32, NaN, Infinity, '2', null, true]) {
  assert.throws(() => engine.createWorld({ bodyCapacity: value }), TypeError);
}
assert.throws(() => world.createBody({ type: 'other', mass: 1 }), TypeError);
assert.throws(() => world.createBody({ mass: 1, shape: { kind: 'circle', radius: 1 } }), TypeError);
assert.throws(() => world.createBody({ mas: 1 }), TypeError);
assert.throws(() => engine.createWorld({ bodyCapacity: 2, sleepEnabled: 1 }), TypeError);
assert.equal(engine.createWorld({ bodyCapacity: 0 }), null);
assert.equal(engine.createWorld({ bodyCapacity: 1, contactHertz: -1 }), null);
const initial = world.readBody(body);
assert.equal(world.setMass(body, 0), false);
assert.equal(world.setPosition(body, { x: 9000, y: 0 }), false);
assert.equal(world.setRestitution(body, 2), false);
assert.deepEqual(world.readBody(body), initial);
assert(world.applyForceAtPoint(body, { x: 0, y: 6 }, { x: 1, y: 0 }));
assert.equal(world.readBody(body).torque, 6);
assert(world.step(1/60));
assert.equal(world.readBody(body).torque, 0);
assert(world.setShape(body, engine.box(1, 1)));
assert.equal(world.readBody(body).shape.vertices.length, 4);
assert(world.setShape(body, world.readBody(body).shape));
assert.equal(world.readBody(body).shape.vertices.length, 4);
const other = engine.createWorld(config);
const otherBody = other.createBody({ mass: 1 });
assert.throws(() => other.readBody(body), /another world/);
assert.throws(() => world.setMass(otherBody, 1), /another world/);
assert.throws(() => world.readBody({ ...body }), /stale/);
assert.equal(other.isBodyValid(body), false);
assert.equal(other.destroyBody(body), false);
const extra = world.createBody({ mass: 1 });
assert(extra);
assert.equal(world.createBody({ mass: 1 }), null);
assert.equal(world.bodyCount, 2);
assert.deepEqual(world.firstBody(), body);
assert.deepEqual(world.nextBody(body), extra);
assert.equal(world.nextBody(extra), null);
assert.equal(world.bodyAt(2), null);
assert(world.destroyBody(body));
assert.equal(world.destroyBody(body), false);
const replacement = world.createBody({ mass: 1 });
assert.equal(replacement.index, body.index);
assert.notEqual(replacement.generation, body.generation);
assert.throws(() => world.readBody(body), /stale/);
world.reset();
assert.equal(world.isBodyValid(replacement), false);
assert.equal(other.isBodyValid(otherBody), true);
assert(world.createBody({ mass: 1 }));
world.dispose(); world.dispose();
assert.throws(() => world.step(1/60), /disposed/);
assert.throws(() => world.bodyCount, /disposed/);
assert.throws(() => world.createBody({ mass: 1 }), /disposed/);
const twinEngine = await createSilk();
const twin = twinEngine.createWorld(config);
const twinBody = twin.createBody({ mass: 1 });
assert.throws(() => other.readBody(twinBody), /another world/);
const heapBeforeSteps = engine.memory.allocatorUsedBytes;
for (let i = 0; i < 300; ++i) { assert(other.step(1/60)); assert(twin.step(1/60)); }
assert.equal(engine.memory.allocatorUsedBytes, heapBeforeSteps);
const a = other.readBody(otherBody), b = twin.readBody(twinBody);
assert.deepEqual(a.position, b.position);
assert.deepEqual(a.velocity, b.velocity);
assert.equal(engine.memory.linearMemoryBytes, 64*1024*1024);
engine.dispose(); engine.dispose();
assert.throws(() => other.step(1/60), /disposed/);
assert.throws(() => engine.circle(1), /disposed/);
assert.throws(() => engine.createWorld(config), /disposed/);
assert(twin.step(1/60));
twinEngine.dispose();
const small = await createSilk({ memoryBytes: 2*1024*1024 });
assert.equal(small.memory.linearMemoryBytes, 2*1024*1024);
assert.equal(small.createWorld({ bodyCapacity: limits.bodies, jointCapacity: limits.joints }), null);
// Failed large allocations must not consume the module's remaining budget.
for (let i = 0; i < 200; ++i) {
  const w = small.createWorld({ bodyCapacity: 16 }); assert(w); w.dispose();
}
const full = [];
for (let i = 0; i < 256; ++i) {
  const w = small.createWorld({ bodyCapacity: 128 });
  if (!w) break;
  full.push(w);
}
assert(full.length > 0 && full.length < 256);
for (const w of full) w.dispose();
assert(small.createWorld({ bodyCapacity: 128 }));
small.dispose();
for (const memoryBytes of [0, 65536, 2097153, 536870913, null, '67108864']) {
  await assert.rejects(createSilk({ memoryBytes }));
}
// Input getters may call application code: disposal must be caught before C.
const reentrant = await createSilk();
const reentrantWorld = reentrant.createWorld(config);
assert.throws(() => reentrantWorld.createBody({ get mass() { reentrantWorld.dispose(); return 1; } }), /disposed/);
assert.throws(() => reentrant.createWorld({ get bodyCapacity() { reentrant.dispose(); return 1; } }), /disposed/);
const { default: rawFactory } = await import(new URL('./silk.mjs', entry));
const fixedMemory = new WebAssembly.Memory({ initial: 32, maximum: 32 });
const raw = await rawFactory({ wasmMemory: fixedMemory });
assert.throws(() => fixedMemory.grow(1), RangeError);
assert(raw._sl_wasm_heap_base() < 2*1024*1024);
const large = await createSilk({ memoryBytes: 256*1024*1024 });
assert.equal(large.memory.linearMemoryBytes, 256*1024*1024);
assert(large.createWorld({ bodyCapacity: limits.bodies, jointCapacity: limits.joints }));
assert(large.memory.allocatorUsedBytes >= large.memory.requestedBytes);
large.dispose();
const api = await createSilk();
const wc = { bodyCapacity: 8, contactCapacity: 32, jointCapacity: 2 };
const w = api.createWorld(wc), isolated = api.createWorld(wc);
assert.equal(w.memory.adapterBytes, api.worldAdapterBytes(wc));
assert.equal(w.memory.outputBytes, 132*wc.bodyCapacity + 136*wc.contactCapacity + 60*wc.jointCapacity);
assert.equal(api.memory.outputBytes, 2*w.memory.outputBytes);
const { queryMasks } = await import(entry);
assert.deepEqual(queryMasks, { dynamic: 1, kinematic: 2, static: 4, all: 7 });
const circleOne = api.circle(1);
const first = w.createBody({ mass: 1, shape: circleOne });
const support = w.createBody({ type: 'static', shape: circleOne, position: { x: 0.5, y: 0 } });
const third = w.createBody({ mass: 1, shape: circleOne, position: { x: 6, y: 0 } });
const foreign = isolated.createBody({ mass: 1 });
assert.equal(w.snapshot.valid, false);
assert.throws(() => w.snapshot.bodyCount, /invalid/);
const query = w.queryPoint(0, 0, 0, 1);
assert.equal(query.count, 2); assert.equal(query.written, 1); assert.equal(query.truncated, true);
assert.deepEqual(query.bodyAt(0), first); assert(w.isBodyValid(query.bodyAt(0)));
const queryVersion = query.revision, queryCopy = query.copy();
assert.equal(w.queryAabb(1, 0, -1, 0), null);
assert.equal(w.queryPoint(0, 0, 8), null);
assert.equal(w.queryPoint(0, 0, 0, 9), null);
assert.throws(() => w.queryPoint(NaN, 0), TypeError);
assert.throws(() => w.queryPoint(0, 0, 0, 0.5), TypeError);
assert(query.isCurrent(queryVersion));
assert.deepEqual(query.copy(), queryCopy);
assert.equal(w.queryPoint(0, 0, queryMasks.dynamic).count, 1);
assert.equal(query.isCurrent(queryVersion), false);
assert.equal(w.queryPoint(0, 0, queryMasks.static).bodyAt(0).index, support.index);
assert.equal(w.queryPoint(0, 0, 0, 0).written, 0);
const sorted = w.queryAabb(-2, -2, 8, 2).copy();
assert.deepEqual(sorted.bodies.map(x => x.index), [first.index, support.index, third.index]);
const ray = w.queryRay(-3, 0, 6, 0), rayVersion = ray.revision, rayCopy = ray.copy();
assert.equal(ray.hit, true); assert.deepEqual(ray.body(), first);
assert(Math.abs(ray.fraction - 1/3) < 1e-6);
assert.equal(w.queryRay(-3, 0, 0, 0), null);
assert(ray.isCurrent(rayVersion)); assert.deepEqual(ray.copy(), rayCopy);
assert.equal(w.queryRay(100, 100, 1, 0).hit, false);
assert.equal(ray.body(), null);
assert(w.refreshSnapshot());
const frame = w.snapshot, revision = frame.revision, retained = frame.copy();
assert.equal(frame.bodyCount, 3); assert.equal(frame.geometryUpdates, 3);
assert.equal(query.valid, false); assert.equal(ray.valid, false);
for (let row = 0; row < frame.bodyCount; ++row) {
  const body = w.readBody(w.bodyAt(row)), slot = frame.bodies.index[row];
  assert.equal(frame.bodies.x[row], body.position.x); assert.equal(frame.bodies.y[row], body.position.y);
  assert.equal(frame.bodies.cos[row], body.rotation.c); assert.equal(frame.bodies.sin[row], body.rotation.s);
  assert.equal(frame.geometry.radius[slot], body.shape.radius);
}
assert.equal(frame.bodies.x.buffer.byteLength, wc.bodyCapacity*4);
assert.equal(query.indices.buffer.byteLength, wc.bodyCapacity*4);
new Uint8Array(frame.bodies.x.buffer).fill(255);
assert(Number.isNaN(frame.bodies.x[0]));
frame.bodies.x[0] = 123;
assert.equal(w.readBody(first).position.x, 0);
assert(w.refreshSnapshot()); assert.equal(frame.geometryUpdates, 0);
assert.equal(frame.bodies.x[0], 0); assert.equal(frame.isCurrent(revision), false);
assert.equal(retained.bodies.x[0], 0);
assert(w.setShape(first, api.box(0.5, 0.5)));
assert.equal(frame.valid, false); assert.throws(() => frame.copy(), /invalid/);
assert(w.refreshSnapshot()); assert.equal(frame.geometryUpdates, 1);
assert.equal(frame.geometry.kind[first.index], 2); assert.equal(frame.geometry.count[first.index], 4);
assert.equal(retained.geometry.kind[first.index], 1);
assert.equal(retained.geometry.radius[first.index], 1);
const rejection = api.createWorld({ bodyCapacity: 1 });
const tinyMass = rejection.createBody({ mass: 1e-30, shape: circleOne });
assert(tinyMass); rejection.refreshSnapshot();
assert.equal(rejection.setShape(tinyMass, api.circle(1e-5)), false);
assert(rejection.refreshSnapshot()); assert.equal(rejection.snapshot.geometryUpdates, 0);
assert.equal(rejection.snapshot.geometry.radius[tinyMass.index], 1);
rejection.dispose();
const joint = w.createJoint({ kind: 'distance', bodyA: first, bodyB: third, length: 6 });
const hinge = w.createJoint({ kind: 'revolute', bodyA: third, bodyB: support, localAnchorB: { x: 5.5, y: 0 } });
assert(joint); assert(hinge); assert.equal(w.jointCount, 2);
assert.equal(w.createJoint({ kind: 'distance', bodyA: first, bodyB: third, length: 6 }), null);
assert.equal(w.createJoint({ kind: 'distance', bodyA: first, bodyB: third, length: -1 }), null);
assert.throws(() => w.createJoint({ kind: 'distance', bodyA: first, bodyB: foreign, length: 6 }), /another world/);
assert.throws(() => w.createJoint({ kind: 'distance', bodyA: first, bodyB: third, length: Infinity }), TypeError);
assert.throws(() => w.createJoint({ kind: 'distance', bodyA: first, bodyB: third, collideConnected: 1 }), TypeError);
assert(w.isJointValid(joint)); assert.equal(w.isBodyValid(joint), false); assert.equal(w.isJointValid(first), false);
assert.equal(w.destroyBody(joint), false); assert.equal(w.destroyJoint(first), false);
assert.throws(() => w.readBody(joint), /stale/); assert.throws(() => w.readJoint(first), /stale/);
assert.throws(() => isolated.readJoint(joint), /another world/);
const jointRead = w.readJoint(joint);
assert.deepEqual(jointRead.bodyA, first); assert(w.isBodyValid(jointRead.bodyB));
assert.equal(jointRead.length, 6); assert.equal(w.readJoint(hinge).kind, 'revolute');
assert.deepEqual(w.jointAt(0), joint); assert.equal(w.jointAt(2), null);
assert(w.step(1/60)); assert(w.refreshSnapshot(true));
assert.equal(frame.jointCount, 2); assert(frame.contactCount > 0);
assert.equal(frame.joints.index[0], joint.index); assert.equal(frame.joints.length[0], w.readJoint(joint).length);
const contact = w.contactAt(0);
assert(w.isBodyValid(contact.bodyA)); assert.equal(frame.contacts.bodyAIndex[0], contact.bodyA.index);
assert.equal(frame.contacts.normalX[0], contact.normal.x);
assert.equal(frame.contacts.normalImpulse0[0], contact.points[0].normalImpulse);
assert.equal(w.contactAt(w.contactCount), null);
assert(w.islandStats(first)); assert.equal(w.islandStats(support), null);
const stats = w.stats(); assert.equal(stats.bodyCount, 3); assert.equal(stats.jointCount, 2);
assert.equal(typeof stats.cumulative.treeNodeVisits, 'bigint');
assert.equal(stats.contactDropCount, 0);
const { workCopy, jsonReplacer } = await import(new URL('./views.mjs', entry));
const wide = new BigUint64Array(26); wide[0] = 9007199254740993n; wide[12] = 18446744073709551615n;
const wideCopy = workCopy(wide); assert.equal(wideCopy.treeNodeVisits, 9007199254740993n);
assert.equal(JSON.parse(JSON.stringify(wideCopy, jsonReplacer)).contactDrops, '18446744073709551615');
const occupied = api.memory.allocatorUsedBytes;
const stableBodies = frame.bodies.x, stableQuery = w.queryPoint(0, 0);
for (let i = 0; i < 100; ++i) {
  w.refreshSnapshot(true); assert.equal(frame.bodies.x, stableBodies);
  assert.equal(w.queryPoint(0, 0), stableQuery);
}
assert.equal(api.memory.allocatorUsedBytes, occupied);
const stepper = w.createStepper(1/60);
assert(stepper); assert.equal(w.createStepper(1e-45), null);
assert(w.advance(stepper, 1)); assert.equal(stepper.steps, 8); assert(stepper.droppedTime > 0.8);
assert.equal(stepper.remainder, 0); assert(w.advance(stepper, -1)); assert.equal(stepper.steps, 0);
assert.throws(() => isolated.advance(stepper, 1/60), /another world/);
assert(w.destroyBody(first)); assert.equal(w.isJointValid(joint), false);
assert.throws(() => w.readJoint(joint), /stale/);
assert.equal(w.isBodyValid(queryCopy.bodies[0]), false);
assert.equal(stableQuery.valid, false);
const reuse = w.createBody({ mass: 1, shape: api.circle(0.75) });
assert.equal(reuse.index, first.index); assert.notEqual(reuse.generation, first.generation);
assert(w.refreshSnapshot()); assert.equal(frame.geometry.radius[reuse.index], 0.75);
assert.equal(frame.geometry.kind[reuse.index], 1); assert.equal(frame.geometry.x0[reuse.index], 0);
w.reset(); assert.equal(w.isJointValid(hinge), false); assert.equal(frame.valid, false);
assert.throws(() => w.advance(stepper, 1/60), /stale/);
assert(w.refreshSnapshot(true)); assert.equal(frame.bodyCount, 0); assert.equal(frame.contactCount, 0); assert.equal(frame.jointCount, 0);
api.dispose(); assert.equal(frame.valid, false); assert.throws(() => frame.copy(), /invalid/);
console.log('Remaining bindings, exact counters, bounded queries/advance, bulk lifetimes, and geometry cache passed');
console.log('WASM lifecycle, validation, shapes, bodies, memory exhaustion, isolation, and replay passed');
